Add helm chart
synalabs/k8s-cleanup pull request #2
Opened 2020-01-09 13:19 UTC by bprsyn

2020-01-14 14:09 UTC, fbaligant commented on helm/k8scleanup/values.yaml
> +  concurrencyPolicy: '"Forbid"'
Si cela doit forcément être quoté, il vaut mieux faire: 
```
{{ .Values.cronJob.concurrencyPolicy | quote }}
```
et avoir la valeur non quotée dans le values

2020-01-14 14:09 UTC, fbaligant commented on helm/k8scleanup/values.yaml
> +  schedule: '"0 */3 * * *"'
Si cela doit forcément être quoté, il vaut mieux faire:
```
{{ .Values.cronJob.schedule | quote }}
```
et avoir la valeur non quotée dans le values

2020-01-14 14:17 UTC, bprsyn commented on helm/k8scleanup/values.yaml
> +  schedule: '"0 */3 * * *"'
Ca ne me donne pas non plus le résultat attendu:
Avec `ressources: {{ .Values.cronJob.ressources | quote }}`
J'ai dans le template généré: `ressources: "[replicasets jobs pods]"`

Alors que j'attend  `ressources: ["replicasets", "jobs" "pods"]` 

Peut être que passer un hash n'est pas un bonne pratique ?

2020-02-10 13:19 UTC, fbaligant requested changes

2020-02-10 13:19 UTC, fbaligant commented on helm/k8scleanup/Chart.yaml
> +description: A Helm chart for Kubernetes
Description a revoir pour y inclure k8s cleanup

2020-02-10 13:19 UTC, fbaligant commented on helm/k8scleanup/templates/cronjob.yaml
> +              resources:
C'est ok comme ça mais la prochaine fois n'hésitez pas à déporter tout resources dans le values.yaml

2020-02-10 17:08 UTC, merged